apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  namespace: default
  labels:
    app: test
spec:
  os:
    name: linux
  containers:
  - name: test_container
    image: registry.bigbrother.io/myapp:v1.0
    resources:
      requests:
        cpu: 100
        memory: 128Mi
      limits:
        cpu: 200
        memory: 256Mi